from sqlalchemy import Column, Date, Integer, String, DateTime
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class UC58HCEmployeeCareer(Base):
    __tablename__ = 'UC58_HC_EmployeeCareer_2'

    id = Column(Integer, primary_key=True)
    emp_no = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    emp_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    emp_status = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    emp_prev_no = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    dt_join = Column(Date)
    dt_rehire_mitra = Column(Date)
    dt_resign = Column(Date)
    dt_birthday = Column(Date)
    company_id = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    company_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    directorate_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))     
    directorate_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))     
    division_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))        
    division_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))        
    department_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))      
    department_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))      
    subdepartment_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))   
    subdepartment_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))   
    section_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    section_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    job_title_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))       
    job_title_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))       
    position_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))        
    position_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))        
    job_grade = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    worklocation_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    worklocation_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    homebase_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    homebase_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    dt_last_career_eff = Column(Date)    
    religion = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    marital_status = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    num_of_dependance = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    place_of_birth = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    psikotest = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    corporate_email = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))      
    mobile_phone_no = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))      
    superior_emp_no = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))      
    superior_emp_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    gender = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    education = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    education_institution_name_major = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    work_experience_1_company = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    work_experience_1_position = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    work_experience_1_start = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    work_experience_1_end = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))        
    resign_reason = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    last_career_type = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))     
    directorate_catalog_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    directorate_catalog_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    division_catalog_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    division_catalog_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    department_catalog_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    department_catalog_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    unit_catalog_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    unit_catalog_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    satuan_kerja_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    satuan_kerja_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))    
    measure_id = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    measure_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    cost_allocation_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS')) 
    cost_allocation_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS')) 
    region_allocation_code = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))
    region_allocation_name = Column(String(collation='SQL_Latin1_General_CP1_CI_AS'))